### ISSUE TITLE
Only transparent when vscode window focused

### ISSUE THREAD

**Issue by izumiiAoba** [illixion/vscode-vibrancy-continued#36]
#### focused
![](https://user-images.githubusercontent.com/39220621/197462753-8b36e53b-a244-49b2-81c2-f18490bd3b8c.png)
#### unfocused
![](https://user-images.githubusercontent.com/39220621/197462899-2e069932-f3c0-4224-a702-e33e11510ae9.png)

**Comment by illixion** [comment]
I think standard macOS windows lose transparency in the background as well, so this could be intentional Electron behavior. I’m not sure how much time I can invest into investigating this, so if someone wants to help look into this, I’d appreciate it.

**Comment by earlAchromatic** [comment]
+1 MacOS terminal windows are always transparent and I would like the same behavior for VS Code. It's a bit distracting for such a big window to change transparency IMO and always switching from window to window when developing.

**Comment by ethansaks** [comment]
> +1 MacOS terminal windows are always transparent and I would like the same behavior for VS Code. It's a bit distracting for such a big window to change transparency IMO and always switching from window to window when developing.

That's a great point! Just tested this and can confirm that terminal doesn't change it's background when focus changes. I wish this extension worked that way. The switching is really annoying and I don't like how the theme looks with vibrancy off.

**Comment by hjnnjh** [comment]
So is there any way to implement transparent when VSCode window is unfocused?

**Comment by tthn0** [comment]
I'm also having this issue on macOS

**Comment by alperenkarip** [comment]
same problem..

**Comment by hiepsolo** [comment]
I got same problem in Mac M1

**Comment by illixion** [comment]
Everyone is currently experiencing this, no need to +1 unless you have something to add.

**Comment by bololodev** [comment]
I believe this is an Electron thing, I've been using Obsidian which is also Electron based and enabled the vibrancy through the console, it behaves exactly like this.

It could be a Windows related issue since the Terminal also has this behavior but if  if macOS users are having the same issue it's probably on Electron's side.

**Comment by RoyalFoxy** [comment]
I have stumbled upon another issue from the old code base which got archived 

https://github.com/EYHN/vscode-vibrancy/issues/127

This is the link to it

In short one comment searched the docs of electron and found out something that would enable vibrancy to be enabled all the time even without focus. This is for macos only btw.

The comment reads
"This is probably happening since BrowserWindow.options.visualEffectState is presumably set to the default value of followWindow. Changing this to active should fix this.

I've figured this out by looking at the [electron docs](https://www.electronjs.org/docs/v14-x-y/api/browser-window#new-browserwindowoptions) (Just ctrl+f for visualEffectState).

Unfortunately I have no idea how to access the options object of a BrowserWindow using an extension or if changing it after its creating is even possible.
I'd appreciate if anyone with any knowledge about electron and vscode extensions could chime in."

So if there is an option to set the visualEffectState option to active in a vscode extension then this issue could be solved.

The link provided in the comment does not work and here is a working alternative to the new page that contains the info about visualEffectState https://www.electronjs.org/docs/latest/api/browser-window#new-browserwindowoptions

**Comment by illixion** [comment]
This is a good find @RoyalFoxy, thanks for mentioning this option! Since we're updating VSCode files directly, I could make Vibrancy modify the `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js` file to add this option to the BrowserWindow creation code. I've tested this locally and it does seems to work as expected.

**Comment by illixion** [comment]
I've published v1.1.18 which fixes this issue, closing as completed.

**Comment by izumiiAoba** [comment]
i already update to v1.1.19, but code window still lost transparency when not focus
<img width="840" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/39220621/78a24674-3cb5-4d3b-997a-732e39921690">

**Comment by illixion** [comment]
Thanks for letting me know @izumiiAoba, there was an implementation bug that I didn't notice, fixed it and verified that this works properly now.

**Comment by izumiiAoba** [comment]
sincerely appreciate your work, but problem still exists even update to v1.1.20.
perhaps it's caused by my VS Code version or some other dependencies?

**Comment by illixion** [comment]
> sincerely appreciate your work, but problem still exists even update to v1.1.20.
> perhaps it's caused by my VS Code version or some other dependencies?

If you have any other extensions that modify VSCode's files, then that's a possibility, I've seen some custom CSS loaders cause issues with Vibrancy for instance.

Could you try opening `/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/code/electron-main/main.js` and searching for `visualEffectState:"active"`? It should be next to `experimentalDarkMode:!0`, and that change is what enables background transparency. If it's missing, you may need to try reloading Vibrancy again.

**Comment by tthn0** [comment]
I uninstalled and reinstalled vibrancy, and I no longer have this bug on `v1.1.20` now.

**Comment by izumiiAoba** [comment]
> and searching for visualEffectState:"active"

this setting is `active`
<img width="923" alt="image" src="https://github.com/illixion/vscode-vibrancy-continued/assets/39220621/1b51fda6-515e-44c9-a722-fb37de9bd04f">


> I uninstalled and reinstalled vibrancy, and I no longer have this bug on v1.1.20 now.

i tried uninstall and install, and works properly🥳
thanks again illixion, tthn0
